name: Generate Rust Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate documentation
        run: cargo doc --release

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Only deploy on main branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc/
